### ISSUE TITLE
OSX installation fails

### ISSUE THREAD

**Issue by nickforddesign** [avalonmediasystem/avalon#1598]
Apologies in advance, I'm a node.js guy and have zero experience with the majority of this environment.

Going through the steps for OSX installation at https://wiki.dlib.indiana.edu/pages/viewpage.action?pageId=513770311, began experiencing problems at this step:
```
svn checkout http://opencast.jira.com/svn/MH/trunk/docs/scripts/3rd_party matterhorn_dependencies
```

The result I get:

```
svn: E170013: Unable to connect to a repository at URL 'https://opencast.jira.com/svn/MH/trunk/docs/scripts/3rd_party'
svn: E175009: The XML response contains invalid XML
svn: E130003: Malformed XML: no element found
```

Is this no longer the location of this repository? Perhaps the set up guide needs to be updated?

I did try to proceed, unsure of whether or not this previous step would be a deal breaker, but got another error trying to run `bundle install --gemfile=Gemfile.first`

```
Installing treetop 1.4.10
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.5.2/ext/nokogiri
/usr/local/opt/ruby/bin/ruby -r ./siteconf20170213-3993-i5rq8y.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.4.0/bin/$(RUBY_BASE_NAME)
extconf.rb:10:in `<main>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
               CONFIG

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.5.2 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-15/2.4.0/nokogiri-1.5.2/gem_make.out

An error occurred while installing nokogiri (1.5.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.5.2'` succeeds before bundling.
```

**Comment by cjcolvar** [comment]
Since you are on OS X, we have development environment install based on docker containers documented here:

https://github.com/avalonmediasystem/avalon/wiki/Configuring-an-OS-X-Development-Environment-With-Docker-Containers

Let us know if you have any questions / comments about those instructions since they are fresh and getting refined right now.

**Comment by nickforddesign** [comment]
Thanks @cjcolvar!

**Comment by nickforddesign** [comment]
Docker installation was fairly smooth (although as soon as I got to networking setup I started getting permissions errors and realized I either needed to be root, or run the following before the last step in networking.md:

```
sudo chown root /Library/LaunchDaemons/com.runlevel1.lo0.172.16.123.1.plist
sudo chown root /Library/LaunchDaemons/com.runlevel1.pf.rails80.plist
sudo chgrp wheel /Library/LaunchDaemons/com.runlevel1.lo0.172.16.123.1.plist
sudo chgrp wheel /Library/LaunchDaemons/com.runlevel1.pf.rails80.plist
sudo chmod o-w /Library/LaunchDaemons/*
```

Then, all smooth until running `docker-compose up`, I got the following back:

```
Creating network "avalon_default" with the default driver
Creating volume "avalon_streaming" with default driver
Creating volume "avalon_work" with default driver
Creating volume "avalon_solr" with default driver
Creating volume "avalon_fedora" with default driver
Creating avalon_redis_1
Creating avalon_streaming_1
Creating avalon_matterhorn_1
Creating avalon_solr_1
Creating avalon_fedora_1

ERROR: for matterhorn  Cannot start service matterhorn: Mounts denied:
The path /masterfiles
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.
```

So I continued onto the masterfiles steps below and shared them with docker, and tried to run `docker-compose up` again, and got this:

```
ERROR: Bad response from Docker engine
```

At this point, I am not quite sure how to proceed debugging this because I am new to Docker. Any recommendations? 

Thank you!

**Comment by cjcolvar** [comment]
@mbklein @carrickr Do either of you two have any ideas here?

**Comment by mbklein** [comment]
Sorry for the delayed response. `Bad response from Docker engine` usually means that the Docker engine is stopped or mid-restart. Adding the `/masterfiles` directory to the share list causes the Docker engine to restart, so it's likely that you simply ran `docker-compose up` before Docker was ready for you.

**Comment by nickforddesign** [comment]
Wow, yes that was the case, sorry I feel like I should have dug deeper on that one. So then it seems the main issue I had with the instructions was the order of the /masterfiles step in relation to starting up docker.

Matterhorn crashed the first time I tried to pull up port 8080, but after restarting docker it is running, along with everything else. Thank you all for your help!

Here's what I got back from matterhorn, just in case:

```
HTTP ERROR 503

Problem accessing /. Reason:

    java.lang.IllegalStateException: Can only register services while bundle is active or activating.
Caused by:

javax.servlet.UnavailableException: java.lang.IllegalStateException: Can only register services while bundle is active or activating.
	at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:458)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.apache.felix.http.jetty.internal.JettyService.initializeJetty(JettyService.java:164)
	at org.apache.felix.http.jetty.internal.JettyService.startJetty(JettyService.java:115)
	at org.apache.felix.http.jetty.internal.JettyService.run(JettyService.java:290)
	at java.lang.Thread.run(Thread.java:745)
