### ISSUE TITLE
Integrate Canvas on fluorine with Avalon on spruce

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2242]
So that we can test LTI on Spruce. First pass couldn't get spruce to work. Details:

> When attempting to use the LTI link within canvas, you get an error because the auth_hash in find_for_lti is nil.  This might be because omniauth-lti is dying somewhere and isn't populating it or some other sort of issue with warden or devise.

```
Started POST "/users/auth/lti/callback" for 149.160.196.196 at 2017-08-24 18:09:00 +0000
  [1m[36mActiveRecord::SchemaMigration Load (0.4ms)[0m  [1mSELECT "schema_migrations".* FROM "schema_migrations"[0m
Processing by Users::OmniauthCallbacksController#lti as HTML
  Parameters: {"oauth_consumer_key"=>"fluorine", "oauth_signature_method"=>"HMAC-SHA1", "oauth_timestamp"=>"1503598139", "oauth_nonce"=>"Cxfxy4oCW5xHt8VFPAAjWZTA213n3Ssh9dsiV1bro", "oauth_version"=>"1.0", "context_id"=>"4dde05e8ca1973bcca9bffc13e1548820eee93a3", "context_label"=>"Phuong", "context_title"=>"Phuong Test", "custom_canvas_enrollment_state"=>"active", "ext_roles"=>"urn:lti:instrole:ims/lis/Administrator,urn:lti:instrole:ims/lis/Instructor,urn:lti:role:ims/lis/Instructor,urn:lti:sysrole:ims/lis/SysAdmin,urn:lti:sysrole:ims/lis/User", "launch_presentation_document_target"=>"iframe", "launch_presentation_locale"=>"en", "launch_presentation_return_url"=>"http://fluorine.dlib.indiana.edu:8980/courses/1/external_content/success/external_tool_redirect", "lti_message_type"=>"basic-lti-launch-request", "lti_version"=>"LTI-1p0", "oauth_callback"=>"about:blank", "resource_link_id"=>"ae06e3eb8ea83588f0a1c5897b98830dc93f47d8", "resource_link_title"=>"Test page", "roles"=>"Instructor,urn:lti:instrole:ims/lis/Administrator", "tool_consumer_info_product_family_code"=>"canvas", "tool_consumer_info_version"=>"cloud", "tool_consumer_instance_contact_email"=>"canvas@example.edu", "tool_consumer_instance_guid"=>"794d72b707af6ea82cfe3d5d473f16888a8366c7.localhost:3000", "tool_consumer_instance_name"=>"Canvas Docker", "user_id"=>"535fa085f22b4655f48cd5a36a9215f64c062838", "oauth_signature"=>"OvHv7XoKFsQ1pXLMXlL3O4dbvHI="}
Attempting to find user with lti strategy
lti :: nil
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `uid' for nil:NilClass):
  app/models/user.rb:61:in `find_for_lti'
  app/controllers/users/omniauth_callbacks_controller.rb:50:in `find_user'
  app/controllers/users/omniauth_callbacks_controller.rb:43:in `action_missing'


  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.7ms)
  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /home/app/gems/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (21.9ms)

```

### Done looks like
Spruce connects to Canvas and embedding works.

**Comment by phuongdh** [comment]
Turns out we should have put this config under development, not test.
