### ISSUE TITLE
Batch IngestStatusCheck rake task fails

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2418]
The IngestStatusCheck rake task checks for batches that are finished processing and sends emails appropriately, but when I ran it manually on spruce it failed with the error below:
```
bundle exec rake avalon:batch:ingest_status_check
/srv/avalon/avalon_r6/releases/20171019005936/config/initializers/fixnum_to_hms.rb:1: warning: constant ::Fixnum is deprecated
rake aborted!
NameError: uninitialized constant IngestFinished
/srv/avalon/avalon_r6/releases/20171019005936/lib/tasks/avalon.rake:229:in `block (3 levels) in <top (required)>'
/srv/avalon/avalon_r6/shared/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home.local/avalon/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/home.local/avalon/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
/home.local/avalon/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
/home.local/avalon/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home.local/avalon/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => avalon:batch:ingest_status_check
(See full trace by running task with --trace)
```

**Comment by joncameron** [comment]
Covered by #2420, will be merged with that issue.

**Comment by cjcolvar** [comment]
The PR didn't deploy to spruce because it was missing a migration for the existing data.

**Comment by cjcolvar** [comment]
I resolved this by manually migrating the data on spruce.
