### ISSUE TITLE
Files With Spaces Causes Errors in Avalon Docker

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3952]
### Description
The ActiveEncode job is bombing when there are spaces in a filename. This was using our Docker setup, on current develop. The job can't find the right file reference after the fact and keeps trying to rerun the same job forever.

### To Reproduce
In our Docker environment, upload a file with spaces.

#### Transcode Dashboard
I'm not sure if this is related, but the filename here isn't correct:
![Screen Shot 2020-01-17 at 4 17 54 PM](https://user-images.githubusercontent.com/1406618/72646791-f2a9e000-3944-11ea-9d3f-0a30216d291d.png)

#### Sidekiq Dashboard
![Screen Shot 2020-01-17 at 4 19 07 PM](https://user-images.githubusercontent.com/1406618/72646873-2127bb00-3945-11ea-839d-28dc84067b10.png)

### Log Snippet
```
worker_1         | 2020-01-17T21:15:05.817Z 7 TID-gqipjf5vr ActiveEncode::PollingJob JID-55c1bc1f6469b940ac8a83fb INFO: start
worker_1         | E: file:///tmp/38acd328-a540-4236-a465-0d903cf31d20/outputs/Cats%20Ringing%20Bells-high.mp4, Couldn't open file /tmp/38acd328-a540-4236-a465-0d903cf31d20/outputs/Cats%20Ringing%20Bells-high.mp4
worker_1         | 2020-01-17T21:15:05.890Z 7 TID-gqipjf5vr ActiveEncode::PollingJob JID-55c1bc1f6469b940ac8a83fb INFO: fail: 0.073 sec
worker_1         | 2020-01-17T21:15:05.890Z 7 TID-gqipjf5vr WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActiveEncode::PollingJob","queue":"default","args":[{"job_class":"ActiveEncode::PollingJob","job_id":"d68d5e99-88d4-4fa2-a615-fc231747a8c7","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://ActiveEncode/FfmpegEncode/38acd328-a540-4236-a465-0d903cf31d20"}],"executions":0,"locale":"en"}],"retry":true,"jid":"55c1bc1f6469b940ac8a83fb","created_at":1579295690.374296,"enqueued_at":1579295705.816254},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActiveEncode::PollingJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"ActiveEncode::PollingJob\",\"job_id\":\"d68d5e99-88d4-4fa2-a615-fc231747a8c7\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://ActiveEncode/FfmpegEncode/38acd328-a540-4236-a465-0d903cf31d20\"}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"55c1bc1f6469b940ac8a83fb\",\"created_at\":1579295690.374296,\"enqueued_at\":1579295705.816254}"}
worker_1         | 2020-01-17T21:15:05.890Z 7 TID-gqipjf5vr WARN: Errno::ENOENT: No such file or directory @ rb_file_s_size - /tmp/38acd328-a540-4236-a465-0d903cf31d20/outputs/Cats Ringing Bells-high.mp4
worker_1         | 2020-01-17T21:15:05.890Z 7 TID-gqipjf5vr WARN: /usr/local/bundle/gems/aws-sdk-resources-2.11.272/lib/aws-sdk-resources/services/s3/file_uploader.rb:31:in `size'
worker_1         | /usr/local/bundle/gems/aws-sdk-resources-2.11.272/lib/aws-sdk-resources/services/s3/file_uploader.rb:31:in `upload'
worker_1         | /usr/local/bundle/gems/aws-sdk-resources-2.11.272/lib/aws-sdk-resources/services/s3/object.rb:252:in `upload_file'
worker_1         | /home/app/avalon/app/models/watched_encode.rb:37:in `block (2 levels) in <class:WatchedEncode>'
worker_1         | /home/app/avalon/app/models/watched_encode.rb:32:in `collect!'
worker_1         | /home/app/avalon/app/models/watched_encode.rb:32:in `block in <class:WatchedEncode>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `instance_exec'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:517:in `block in invoke_after'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:517:in `each'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:517:in `invoke_after'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:133:in `run_callbacks'
worker_1         | /usr/local/bundle/gems/active_encode-0.7.0/app/jobs/active_encode/polling_job.rb:12:in `perform'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/execution.rb:39:in `block in perform_now'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/disable.rb:44:in `block (2 levels) in <module:Disable>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/throttle.rb:50:in `block (2 levels) in <module:Throttle>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/concurrency.rb:56:in `block (2 levels) in <module:Concurrency>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/logging.rb:46:in `block in tag_logger'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/logging.rb:46:in `tag_logger'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/execution.rb:38:in `perform_now'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/execution.rb:24:in `block in execute'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:83:in `wrap'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/execution.rb:22:in `execute'
worker_1         | /usr/local/bundle/gems/activejob-5.2.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:164:in `block in process'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:109:in `local'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:43:in `block in call'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
worker_1         | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:42:in `call'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:250:in `stats'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
worker_1         | /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by joncameron** [comment]
Merged with #3926
