### ISSUE TITLE
Browse-everything not refreshing Google Drive token

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4305]
### Steps:
- Edit an item
- Open Dropbox
- Connect to Google Drive
- Wait an hour or so and try again

Dropbox fails if the auth token has expired. Browse-everything should refresh Google Drive token using user's cached refresh token.

### Done looks like
- Dropbox works even when token has expired.

**Comment by phuongdh** [comment]
Need to QA non-Google Drive dropbox on Spruce and locally.

**Comment by joncameron** [comment]
Received an error attempting to use non-Google Drive dropbox on Spruce:
```
LoadError in MasterFilesController#create
cannot load such file -- aws-sdk-elastictranscoder



class ElasticTranscoderEncode < WatchedEncode
  self.engine_adapter = :elastic_transcoder

  before_create prepend: true do |encode|
    encode.options.merge!(pipeline_id: Settings.encoding.pipeline,

Rails.root: /srv/avalon/avalon_r6/releases/20201218144032
Application Trace | Framework Trace | Full Trace

app/models/elastic_transcoder_encode.rb:18:in `<class:ElasticTranscoderEncode>'
app/models/elastic_transcoder_encode.rb:17:in `<top (required)>'
app/jobs/active_encode_jobs.rb:17:in `<module:ActiveEncodeJobs>'
app/jobs/active_encode_jobs.rb:15:in `<top (required)>'
app/models/master_file.rb:257:in `process'
app/services/master_file_builder.rb:56:in `block in from_specs'
app/services/master_file_builder.rb:36:in `each'
app/services/master_file_builder.rb:36:in `from_specs'
app/services/master_file_builder.rb:30:in `build'
app/controllers/master_files_controller.rb:230:in `create'

This error occurred while loading the following files:
   elastic_transcoder_encode
   /srv/avalon/avalon_r6/shared/bundle/ruby/2.5.0/bundler/gems/active_encode-58edbae2d5f6/lib/active_encode/engine_adapters/elastic_transcoder_adapter.rb
   aws-sdk-elastictranscoder

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"nQ6fN1NFdDVnf08RqdAt4pkmrZYtY3xO5M2TVf/fv7SMse5usdMNG/kmgsXk/zjHBKFq5JZjtQfCSRyfMm3dhA==",
 "workflow"=>"",
 "container_id"=>"bc386j44x",
 "selected_files"=>{"0"=>{"url"=>"file:///srv/avalon/dropbox/Fancy_Dog/assets/jazz-performance.mp3", "file_name"=>"jazz-performance.mp3", "file_size"=>"2614033"}}}

Toggle session dump

_csrf_token: "yqFfmzKQFNyDkk308gXiIPJ0353bY+v/cBZOet9lwOs="
history: [19017]
search: {"id"=>19017}
user_return_to: "/master_files"
warden.user.user.key: [[21], "$2a$11$gTegbsVXDNp4Njfhfh1HFu"]
warden.user.user.session: {}

Toggle env dump

HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.5"
HTTP_ORIGIN: "https://spruce.dlib.indiana.edu"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "149.161.128.206"
SERVER_NAME: "spruce.dlib.indiana.edu"
SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

None

```

**Comment by joncameron** [comment]
Normal dropbox ingest is working on Spruce. Moving to Done.
