### ISSUE TITLE
WebVTT Files Don't Render When Ending With No Cue Text

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4899]
# Current Behavior
When a VTT file ends with a cue that does not have text associated, the closed captions do not display in the player.

## VTT Example
```
00:24:25.760 --> 00:24:29.110 align:middle line:90%
[MUSIC PLAYING]

00:24:29.110 --> 00:25:56.000 align:middle line:90%
EOF
```

# Expected Behavior
VTT files display normally when the file ends with a timecode without text information

# MediaElement Error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at Object.parse (mejs4_player-89828209b971fb12ea982fda09f81057bdb20080daac76da242fa939497e715d.js:13:29932)
    at mejs4_player-89828209b971fb12ea982fda09f81057bdb20080daac76da242fa939497e715d.js:13:23090
    at a.onreadystatechange (mejs4_player-89828209b971fb12ea982fda09f81057bdb20080daac76da242fa939497e715d.js:16:18387)
```

**Comment by Dananji** [comment]
@joncameron I think, this issue was reported earlier (#3668)?
Brian had put in a fix for that (#3675) for it then, and it was pushed upstream.

**Comment by joncameron** [comment]
@Dananji Testing again on dev the error is different (Uncaught TypeError: text is undefined) but the behavior is still the same—the VTT file does not render.

Example item with two sections: https://avalon-dev.dlib.indiana.edu/media_objects/1z40ks800

**Comment by joncameron** [comment]
@joncameron Upload an example file.

**Comment by joncameron** [comment]
[example - no final cue text.vtt.txt](https://github.com/avalonmediasystem/avalon/files/10134320/example.-.no.final.cue.text.vtt.txt)
