### ISSUE TITLE
Internal Server Error When Loading Item Media Objects

### ISSUE THREAD

**Issue by sgurnick** [avalonmediasystem/avalon#5286]
**Describe the bug**
After following the upgrade path from Avalon `7.2.1` to `7.6`, which also upgrades Ruby from `2.5.X` to `2.7.X` to `3.X`, I'm encountering a consistent internal server error log message when I'm at the screen that loads media objects associated with an item.

**To Reproduce**
Steps to reproduce the behavior, including the results:

1. Log-in to Avalon as a valid user with privileges to view collections and items
2. Click on **Collections** in the top nav bar
3. Click on an available Collection
4. Click on an available Item within the Collection
5. On the next screen that shows all media objects associated with the Item, everything appears to load, but in the `production.log` file I see the following error message:
```
I, [2023-08-02T11:50:27.373449 #93448]  INFO -- : [b85ec2ec-0907-4159-9a39-8d1c08ac2af4] Started GET "/media_objects/xw42nb410" for 162.196.179.194 at 2023-08-02 11:50:27 -0700
I, [2023-08-02T11:50:27.375838 #93448]  INFO -- : [b85ec2ec-0907-4159-9a39-8d1c08ac2af4] Processing by MediaObjectsController#show as HTML
I, [2023-08-02T11:50:27.375992 #93448]  INFO -- : [b85ec2ec-0907-4159-9a39-8d1c08ac2af4]   Parameters: {"id"=>"xw42nb410"}
I, [2023-08-02T11:50:28.170736 #93448]  INFO -- : [b85ec2ec-0907-4159-9a39-8d1c08ac2af4]   Rendered media_objects/show.html.erb within layouts/avalon (Duration: 334.2ms | Allocations: 210974)
I, [2023-08-02T11:50:28.176420 #93448]  INFO -- : [b85ec2ec-0907-4159-9a39-8d1c08ac2af4]   Rendered layout layouts/avalon.html.erb (Duration: 339.9ms | Allocations: 214608)
I, [2023-08-02T11:50:28.176793 #93448]  INFO -- : [b85ec2ec-0907-4159-9a39-8d1c08ac2af4] Completed 200 OK in 801ms (Views: 167.1ms | ActiveRecord: 75.9ms | LDP: 271.6ms | Solr: 73.2ms | Allocations: 511706)
I, [2023-08-02T11:50:29.385865 #93448]  INFO -- : [54156ee6-3f2b-4d91-9bb0-295f2864366e] Started GET "/master_files/zk51vk53n/auto.m3u8?token=[FILTERED]" for 162.196.179.194 at 2023-08-02 11:50:29 -0700
I, [2023-08-02T11:50:29.388564 #93448]  INFO -- : [54156ee6-3f2b-4d91-9bb0-295f2864366e] Processing by MasterFilesController#hls_manifest as */*
I, [2023-08-02T11:50:29.388696 #93448]  INFO -- : [54156ee6-3f2b-4d91-9bb0-295f2864366e]   Parameters: {"token"=>"[FILTERED]", "id"=>"zk51vk53n", "quality"=>"auto"}
I, [2023-08-02T11:50:29.742009 #93448]  INFO -- : [54156ee6-3f2b-4d91-9bb0-295f2864366e] Completed 500 Internal Server Error in 353ms (ActiveRecord: 8.9ms | LDP: 158.2ms | Solr: 18.6ms | Allocations: 243119)
F, [2023-08-02T11:50:29.742585 #93448] FATAL -- : [54156ee6-3f2b-4d91-9bb0-295f2864366e]
[54156ee6-3f2b-4d91-9bb0-295f2864366e] Errno::ENOENT (No such file or directory @ rb_sysopen - https://WOWZA_URL/avalon/_definst_/mp4:42d9e67f-f7c9-4ee8-9636-f839913647a0/outputs/cda12621d1-05-high.mp4/playlist.m3u8?token=FILTERED):
[54156ee6-3f2b-4d91-9bb0-295f2864366e]
[54156ee6-3f2b-4d91-9bb0-295f2864366e] lib/avalon/m3u8_reader.rb:27:in `initialize'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] lib/avalon/m3u8_reader.rb:27:in `open'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] lib/avalon/m3u8_reader.rb:27:in `read'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] app/controllers/master_files_controller.rb:432:in `unnest_wowza_stream'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] app/controllers/master_files_controller.rb:420:in `block in gather_hls_streams'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] app/controllers/master_files_controller.rb:420:in `each'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] app/controllers/master_files_controller.rb:420:in `gather_hls_streams'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] app/controllers/master_files_controller.rb:321:in `hls_manifest'
[54156ee6-3f2b-4d91-9bb0-295f2864366e] config/initializers/ldp_solr_duration_logger.rb:25:in `process_action'
```

**Investigation/Troubleshooting**

_PART 1_
This [stackoverflow post](https://stackoverflow.com/questions/65937714/no-such-file-or-directory-rb-sysopen-for-external-url-rails-6-11-ruby-3) suggests this error message is related to the version of Ruby we are using. 

The implication is in `lib/avalon/m3u8_reader.rb` on line 27:

https://github.com/avalonmediasystem/avalon/blob/524f197a66785fc8fc0e63a59fe8bd7253852205/lib/avalon/m3u8_reader.rb#L27

needs to be changed to:
```
URI.open(io, "Referer" => Rails.application.routes.url_helpers.root_url) { |resp| new(resp, Addressable::URI.parse(io), recursive: recursive) }
```

_PART 2_
When I make this change in my local set-up, I get a new internal server error message:
```
I, [2023-08-02T11:52:08.325155 #93795]  INFO -- : [dc20ccfe-f296-491e-8ec0-15fdab8c591f] Started GET "/media_objects/xw42nb410" for 162.196.179.194 at 2023-08-02 11:52:08 -0700
I, [2023-08-02T11:52:08.327517 #93795]  INFO -- : [dc20ccfe-f296-491e-8ec0-15fdab8c591f] Processing by MediaObjectsController#show as HTML
I, [2023-08-02T11:52:08.327635 #93795]  INFO -- : [dc20ccfe-f296-491e-8ec0-15fdab8c591f]   Parameters: {"id"=>"xw42nb410"}
I, [2023-08-02T11:52:09.125616 #93795]  INFO -- : [dc20ccfe-f296-491e-8ec0-15fdab8c591f]   Rendered media_objects/show.html.erb within layouts/avalon (Duration: 320.9ms | Allocations: 210976)
I, [2023-08-02T11:52:09.131383 #93795]  INFO -- : [dc20ccfe-f296-491e-8ec0-15fdab8c591f]   Rendered layout layouts/avalon.html.erb (Duration: 326.7ms | Allocations: 214610)
I, [2023-08-02T11:52:09.131714 #93795]  INFO -- : [dc20ccfe-f296-491e-8ec0-15fdab8c591f] Completed 200 OK in 804ms (Views: 161.5ms | ActiveRecord: 72.1ms | LDP: 278.0ms | Solr: 74.7ms | Allocations: 511705)
I, [2023-08-02T11:52:09.783694 #93795]  INFO -- : [014f003c-9c00-48d6-820e-21491f25593a] Started GET "/master_files/zk51vk53n/auto.m3u8?token=[FILTERED]" for 162.196.179.194 at 2023-08-02 11:52:09 -0700
I, [2023-08-02T11:52:09.786208 #93795]  INFO -- : [014f003c-9c00-48d6-820e-21491f25593a] Processing by MasterFilesController#hls_manifest as */*
I, [2023-08-02T11:52:09.786333 #93795]  INFO -- : [014f003c-9c00-48d6-820e-21491f25593a]   Parameters: {"token"=>"[FILTERED]", "id"=>"zk51vk53n", "quality"=>"auto"}
I, [2023-08-02T11:52:10.241377 #93795]  INFO -- : [014f003c-9c00-48d6-820e-21491f25593a] Completed 500 Internal Server Error in 455ms (ActiveRecord: 8.5ms | LDP: 159.6ms | Solr: 19.8ms | Allocations: 244741)
F, [2023-08-02T11:52:10.243115 #93795] FATAL -- : [014f003c-9c00-48d6-820e-21491f25593a]
[014f003c-9c00-48d6-820e-21491f25593a] NoMethodError (undefined method `lines' for #<StringIO:0x00007ff5120b5a90 @base_uri=#<URI::HTTPS https://WOW_URL/avalon/_definst_/mp4:42d9e67f-f7c9-4ee8-9636-f839913647a0/outputs/cda12621d1-05-high.mp4/playlist.m3u8?token=FILTERED>, @meta={"accept-ranges"=>"bytes", "access-control-expose-headers"=>"Date, Server, Content-Type, Content-Length, ETag", "cache-control"=>"no-cache", "access-control-allow-origin"=>"*", "etag"=>"\"FILTERED\"", "access-control-allow-credentials"=>"true", "access-control-allow-methods"=>"OPTIONS, GET, POST, HEAD", "connection"=>"Keep-Alive", "access-control-allow-headers"=>"Content-Type, User-Agent, If-Modified-Since, Cache-Control, Range", "date"=>"Wed, 02 Aug 2023 18:52:10 GMT", "content-type"=>"application/vnd.apple.mpegurl", "content-length"=>"153"}, @metas={"accept-ranges"=>["bytes"], "access-control-expose-headers"=>["Date, Server, Content-Type, Content-Length, ETag"], "cache-control"=>["no-cache"], "access-control-allow-origin"=>["*"], "etag"=>["\"FILTERED\""], "access-control-allow-credentials"=>["true"], "access-control-allow-methods"=>["OPTIONS, GET, POST, HEAD"], "connection"=>["Keep-Alive"], "access-control-allow-headers"=>["Content-Type, User-Agent, If-Modified-Since, Cache-Control, Range"], "date"=>["Wed, 02 Aug 2023 18:52:10 GMT"], "content-type"=>["application/vnd.apple.mpegurl"], "content-length"=>["153"]}, @status=["200", "OK"]>):
[014f003c-9c00-48d6-820e-21491f25593a]
[014f003c-9c00-48d6-820e-21491f25593a] lib/avalon/m3u8_reader.rb:41:in `initialize'
[014f003c-9c00-48d6-820e-21491f25593a] lib/avalon/m3u8_reader.rb:28:in `new'
[014f003c-9c00-48d6-820e-21491f25593a] lib/avalon/m3u8_reader.rb:28:in `block in read'
[014f003c-9c00-48d6-820e-21491f25593a] lib/avalon/m3u8_reader.rb:28:in `read'
[014f003c-9c00-48d6-820e-21491f25593a] app/controllers/master_files_controller.rb:432:in `unnest_wowza_stream'
[014f003c-9c00-48d6-820e-21491f25593a] app/controllers/master_files_controller.rb:420:in `block in gather_hls_streams'
[014f003c-9c00-48d6-820e-21491f25593a] app/controllers/master_files_controller.rb:420:in `each'
[014f003c-9c00-48d6-820e-21491f25593a] app/controllers/master_files_controller.rb:420:in `gather_hls_streams'
[014f003c-9c00-48d6-820e-21491f25593a] app/controllers/master_files_controller.rb:321:in `hls_manifest'
[014f003c-9c00-48d6-820e-21491f25593a] config/initializers/ldp_solr_duration_logger.rb:25:in `process_action'
```
This led me to look at [the available methods for the StringIO class](https://ruby-doc.org/3.2.2/exts/stringio/table_of_contents.html) for Ruby 3.2.2. There is no `lines` method, which is used on line 40:

https://github.com/avalonmediasystem/avalon/blob/524f197a66785fc8fc0e63a59fe8bd7253852205/lib/avalon/m3u8_reader.rb#L40

I adjusted line 40 to this in my local enviroment:
```
playlist.each do |l|
```

Following this change, there are no more internal server errors in the log when I load the media objects page for an Item - associated log snippet after changes:

```
I, [2023-08-02T11:53:37.443890 #94086]  INFO -- : [6500e077-03ad-468f-97a4-5bbb2a67a581] Started GET "/media_objects/xw42nb410" for 162.196.179.194 at 2023-08-02 11:53:37 -0700
I, [2023-08-02T11:53:37.446875 #94086]  INFO -- : [6500e077-03ad-468f-97a4-5bbb2a67a581] Processing by MediaObjectsController#show as HTML
I, [2023-08-02T11:53:37.447033 #94086]  INFO -- : [6500e077-03ad-468f-97a4-5bbb2a67a581]   Parameters: {"id"=>"xw42nb410"}
I, [2023-08-02T11:53:38.259732 #94086]  INFO -- : [6500e077-03ad-468f-97a4-5bbb2a67a581]   Rendered media_objects/show.html.erb within layouts/avalon (Duration: 337.0ms | Allocations: 210972)
I, [2023-08-02T11:53:38.265829 #94086]  INFO -- : [6500e077-03ad-468f-97a4-5bbb2a67a581]   Rendered layout layouts/avalon.html.erb (Duration: 343.1ms | Allocations: 214606)
I, [2023-08-02T11:53:38.266169 #94086]  INFO -- : [6500e077-03ad-468f-97a4-5bbb2a67a581] Completed 200 OK in 819ms (Views: 174.3ms | ActiveRecord: 70.8ms | LDP: 277.9ms | Solr: 70.1ms | Allocations: 511242)
I, [2023-08-02T11:53:38.814529 #94086]  INFO -- : [d83d6ab9-e6fc-4d28-bdde-60b55c10129f] Started GET "/master_files/zk51vk53n/auto.m3u8?token=[FILTERED]" for 162.196.179.194 at 2023-08-02 11:53:38 -0700
I, [2023-08-02T11:53:38.817230 #94086]  INFO -- : [d83d6ab9-e6fc-4d28-bdde-60b55c10129f] Processing by MasterFilesController#hls_manifest as */*
I, [2023-08-02T11:53:38.817355 #94086]  INFO -- : [d83d6ab9-e6fc-4d28-bdde-60b55c10129f]   Parameters: {"token"=>"[FILTERED]", "id"=>"zk51vk53n", "quality"=>"auto"}
I, [2023-08-02T11:53:39.323012 #94139]  INFO -- : [81215dc0-50a3-4c50-a678-074f3a1384dd] Started GET "/media_objects/mejs-controls.svg" for 162.196.179.194 at 2023-08-02 11:53:39 -0700
I, [2023-08-02T11:53:39.331875 #94139]  INFO -- : [81215dc0-50a3-4c50-a678-074f3a1384dd] Processing by MediaObjectsController#show as SVG
I, [2023-08-02T11:53:39.331951 #94139]  INFO -- : [81215dc0-50a3-4c50-a678-074f3a1384dd]   Parameters: {"id"=>"mejs-controls"}
I, [2023-08-02T11:53:39.350092 #94139]  INFO -- : [81215dc0-50a3-4c50-a678-074f3a1384dd] Attempted to init base path ``, but it already exists
I, [2023-08-02T11:53:39.360342 #94086]  INFO -- : [d83d6ab9-e6fc-4d28-bdde-60b55c10129f]   Rendered master_files/hls_manifest.m3u8.erb (Duration: 4.8ms | Allocations: 1131)
I, [2023-08-02T11:53:39.360643 #94086]  INFO -- : [d83d6ab9-e6fc-4d28-bdde-60b55c10129f] Completed 200 OK in 543ms (Views: 3.3ms | ActiveRecord: 11.0ms | LDP: 172.3ms | Solr: 19.4ms | Allocations: 248078)
I, [2023-08-02T11:53:39.367570 #94139]  INFO -- : [81215dc0-50a3-4c50-a678-074f3a1384dd]   Rendered errors/unknown_pid.html.erb within layouts/avalon (Duration: 0.7ms | Allocations: 177)
I, [2023-08-02T11:53:39.458167 #94139]  INFO -- : [81215dc0-50a3-4c50-a678-074f3a1384dd]   Rendered layout layouts/avalon.html.erb (Duration: 91.4ms | Allocations: 34072)
```

**Environment:**
- Avalon is running within Passenger on a virtual machine in VMWare
- OS: RHEL 7
- Ruby: 3.2.2

**Release:**
My assumption is this is a compatibility issue in Avalon 7.6 when upgrading to Ruby 3.X.

**Comment by cjcolvar** [comment]
We ran into this as well when upgrading and for some reason I thought it might be specific to our environment so didn't bring the fix back into core avalon at the time.  I put the change that we've been running in #5287.  I think we have seen some small errors from time to time with our solution so curious to see if your solution is better.  Would you be able to open a pull request?

**Comment by cjcolvar** [comment]
Could you make the PR from a fork?  You can use the GitHub edit feature (the little pencil button in the upper right when looking at a file) and it will help create a fork and PR.

**Comment by sgurnick** [comment]
@cjcolvar PR https://github.com/avalonmediasystem/avalon/pull/5288 ready for review.

**Comment by cjcolvar** [comment]
Thanks! I'll take a look and see which works out best.
